# Generated by Django 2.0.7 on 2018-07-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='name',
            field=models.CharField(default='SomeName', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='name',
            field=models.CharField(default='SomeName', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='SomeName', max_length=128),
            preserve_default=False,
        ),
    ]
