# Generated by Django 2.0.7 on 2018-07-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(max_length=3)),
                ('time_part_size', models.IntegerField(default=30)),
                ('coach_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CoachProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTimeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_value', models.DateTimeField()),
                ('is_taken', models.BooleanField()),
                ('is_approved', models.BooleanField()),
                ('is_completed', models.BooleanField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CoachProfile')),
                ('gamer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.GamerProfile')),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tariff_type', models.CharField(choices=[('TRL', 'Trial'), ('LSS', 'Lesson'), ('PCK', 'Lessons Pack'), ('OTH', 'Other')], max_length=3)),
                ('duration', models.IntegerField(default=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='tariff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lessons.Tariff'),
        ),
    ]
